baseURL: 'http://mikeyan.xyz/'
languageCode: 'en-us'
title: "Mike's Digital Garden"
theme: 'PaperMod'

#theme tutorial: https://github.com/adityatelange/hugo-PaperMod/wiki/Features#home-info-mode
params:
    env: production
    #theme
    defaultTheme: auto

    #share
    ShowShareButtons: true

    #profile
    homeInfoParams:
        Title: Hi there ğŸ‘‹
        Content: "I'm a tech lead with a product mindset, astrophotographer, traveller âœˆï¸ book Lover ğŸ“– obsessed with stars âœ¨ 
                Live in ğŸ‡¨ğŸ‡³ ğŸ‡¬ğŸ‡§ ğŸ‡ºğŸ‡¸"
    socialIcons:
            - name: "github"
              url: "https://github.com/ycy1992911"
            - name: "rss"
              url: "https://mikeyan.xyz/index.xml"

    #posts related on the home page
    ShowReadingTime: true
    ShowBreadCrumbs: true
    ShowPostNavLinks: true

    ShowToc: true
    ShowPostNavLinks: true
    ShowCodeCopyButtons: true


    #giscus
    giscus:
        enable: true
        data_repo: "ycy1992911/giscus"
        data_repo_id: "R_kgDOHJu_Cw"
        data_category: "General"
        data_category_id: "DIC_kwDOHJu_C84COgDH"
        data_mapping: "url"
        data_reactions_enabled: "1"
        data_emit_metadata: "0"
        data_input_position: "bottom"
        data_theme: "light"
        data_language: "en"
        crossorigin: "anonymous"

    #search function
    fuseOpts: 
        isCaseSensitive: false
        shouldSort: true
        location: 0
        distance: 1000
        threshold: 0.4
        minMatchCharLength: 0
        keys: ["title", "permalink", "summary", "content"]


#menu
menu:
  main:
    # - identifier: astrophotography
    #   name: Astrophotography
    #   url: /categories/astrophotography/
    #   weight: 5
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30

#search related
outputs:
    home:
        - HTML
        - RSS
        - JSON

Copyright: "Copyright "